name: rmpc
base: core24
version: 'latest'
summary: A configurable, terminal based Media Player Client with album art support
description: |
  Rmpc is a beautiful, modern and configurable terminal based Music Player Daemon client. It was inspired by ncmpcpp and aims to provide an alternative with support for album art through kitty image protocol without any ugly hacks. It also features ranger/lf inspired browsing of songs and other goodies.
  Written by Mierak on Github. Find the upstream code at https://github.com/mierak/rmpc and documentation on their website https://mierak.github.io/rmpc/

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode

parts:
  rmpc:
    source: https://github.com/mierak/rmpc.git
    plugin: rust
  mpd:
    plugin: nil
    stage-packages:
      - mpd
      - libaudio2
      - samba-libs
  mpc:
    plugin: nil
    stage-packages:
      - mpc
  configuration:
    plugin: dump
    source: snap/local/config/
    source-type: local
    organize:
      '*': etc/rmpc/

apps:
  rmpc:
    command: bin/rmpc --config $SNAP_COMMON/config.ron
    plugs:
      - audio-playback
      - network
      - network-bind
    environment:
      RMPC_CONFIG: $SNAP_COMMON/config.ron
  mpd:
    command: usr/bin/mpd --no-daemon $SNAP/etc/rmpc/mpd.conf
    daemon: simple
    plugs:
      - audio-playback
      - network
      - network-bind
    environment:
      MPD_CONFIG: $SNAP/etc/rmpc/mpd.conf
      "LD_LIBRARY_PATH": "$LD_LIBRARY_PATH:$SNAP/usr/lib/x86_64-linux-gnu/blas:$SNAP/usr/lib/x86_64-linux-gnu/lapack:$SNAP/usr/lib/x86_64-linux-gnu/samba:$SNAP/usr/lib/x86_64-linux-gnu/pulseaudio"
      PULSE_SERVER: unix:/run/user/1000/pulse/native
  mpc:
    command: usr/bin/mpc
    plugs:
      - network
      - network-bind