name: rmpc # you probably want to 'snapcraft register <name>'
base: core24 # the base snap is the execution environment for this snap
version: 'latest' # just for humans, typically '1.2+git' or '1.3.2'
summary: A configurable, terminal based Media Player Client with album art support
description: |
  Rmpc is a beautiful, modern and configurable terminal based Music Player Daemon client. It was inspired by ncmpcpp and aims to provide an alternative with support for album art through kitty image protocol without any ugly hacks. It also features ranger/lf inspired browsing of songs and other goodies.
  Written by Mierak on Github. Find the upstream code at https://github.com/mierak/rmpc and documentation on their website https://mierak.github.io/rmpc/

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  rmpc:
    source: .
    plugin: rust

apps:
  rmpc:
    command: /bin/rmpc
    plugs:
      - home
      - audio-playback
      - rmpc-files
      - network
      - network-bind

plugs:
  rmpc-files:
    interface: personal-files
    read:
      - $HOME/.config/rmpc
      - $HOME/.config/rmpc/playlists
      - $HOME/.config/rmpc/tag_cache # db file
      - $HOME/.config/rmpc/state # state file
      - $HOME/.config/rmpc/sticker.sql # sticker file
    write:
      - $HOME/.config/rmpc/playlists
      - $HOME/.config/rmpc/tag_cache # db file
      - $HOME/.config/rmpc/state # state file
      - $HOME/.config/rmpc/sticker.sql # sticker file

