#!/bin/sh
set -e
mkdir -p "$SNAP_COMMON/Music"
mkdir -p "$SNAP_COMMON/playlists"
mkdir -p "$SNAP_COMMON/log"
if [ ! -f "$SNAP_COMMON/config.ron" ]; then
  cp "$SNAP/etc/rmpc/config.ron" "$SNAP_COMMON/config.ron"
fi
if [ ! -d "$SNAP_COMMON/mpd" ]; then
    mkdir "$SNAP_COMMON/mpd"
    chmod 775 "$SNAP_COMMON/mpd"
    chown snap_daemon "$SNAP_COMMON/mpd"
fi