#!/bin/sh
set -e
mkdir -p "$SNAP_COMMON/Music" # Use of this directory is optional
mkdir -p "$SNAP_COMMON/playlists" # This needs to be set in mpd.conf
mkdir -p "$SNAP_COMMON/log" # This is optional as you can use systemd logging for mpd

if [ ! -f "$SNAP_COMMON/config.ron" ]; then
  cp "$SNAP/etc/rmpc/config.ron" "$SNAP_COMMON/config.ron"
fi

chmod +w "$SNAP_COMMON/config.ron"